# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Imaginato' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Museum
    pod 'Alamofire','~> 4.7.3'
    pod 'IQKeyboardManagerSwift'
    pod 'Toast-Swift'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'SDWebImage'
    pod 'NVActivityIndicatorView'


end
